name: Build Huawei-Kirin710-KSU-EMUI9.1.0-Kernel
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y software-properties-common

        sudo apt-get install -y \
          binutils make python3 python3-pip libssl-dev flex unzip ca-certificates \
          xz-utils cpio device-tree-compiler git git-lfs bc bison build-essential \
          ccache curl g++-multilib gcc-multilib gnupg gperf imagemagick \
          libelf-dev liblz4-tool libncurses5-dev libncurses6 libsdl2-dev \
          libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev adb fastboot

        sudo ln -sf /usr/bin/python3 /usr/bin/python
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: Build 8X-KSU-Kernel
      run: |
        rm -rf Kirin710_EMUI_9.1.0*.img
        bash synckernelsu_all.sh
        bash clean.sh
        export HW_DEFCONFIG=JSN_kirin710_KSU_defconfig
        bash Build_kernel_github.sh

    - name: Upload 8X-KSU-Kernel
      uses: actions/upload-artifact@v7
      with:
        name: 8X-Kirin710_KSU-kernel-${{ steps.get_time.outputs.TIME }}
        path: "Kirin710_EMUI_9.1.0*.img"
